name: 'Setup Node environment'
description: 'Setup Node version from nvmrc file'
outputs:
  NODE_VERSION:
    description: 'Node version'
    value: ${{ steps.nvmrc.outputs.NODE_VERSION }}

runs:
  using: "composite"
  steps:
    - name: Read .nvmrc
      shell: bash
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvmrc
    - name: Use Node.js "${{ steps.nvm.outputs.NVMRC }}"
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}