name: "[PR] Run all tests"
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_ENV: development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: './.github/actions/setup-node'
      - run: npm ci
      - run: npm run build --if-present
      - name: Run tests with coverage
        run: npm test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
